sudo: required
services:
  - docker
language: python
python:
  - '3.6'
before_install:
  # See https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg
install:
  - sudo docker --version
  - sudo docker-compose --version
jobs:
  include:
    - stage: test
      script: ./dev ci test_suite
    - script: ./dev ci style
    - stage: production deployment
        name: "Deploy application"
        script: skip
        deploy:
          - provider: script
            script: bash ./infrastructure/prod-deploy/deploy-app.sh
            skip_cleanup: true
            on:
              branch: issue/177  # For testing purposes
      - script: skip
        name: "Update content"
        deploy:
          - provider: script
            script: bash ./infrastructure/prod-deploy/update-content.sh
            skip_cleanup: true
            on:
              branch: issue/177  # For testing purposes
notifications:
  email: false
  slack:
    rooms: deptfunstuff:abJKvzApk5SKtcEyAgtswXAv
    on_success: change
    on_failure: change
stages:
  - name: test
