sudo: required
services:
  - docker
language: python
python:
  - '3.6'
before_install:
  # See https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg
install:
  - sudo docker --version
  - sudo docker-compose --version
jobs:
  include:
    - stage: test
      script: ./dev ci test_suite
    - script: ./dev ci style
    - stage: deployment
      script: skip
      name: "Deploy app to Google App Engine"
      deploy:
        - provider: script
          script: bash ./infrastructure/prod-deploy/deploy-app.sh
          skip_cleanup: true
          on:
            branch: develop
    - script: skip
      name: "Update Google Cloud SQL database"
      deploy:
        - provider: script
          script: bash ./infrastructure/prod-deploy/update-content.sh
          skip_cleanup: true
          on:
            branch: develop
    - script: skip
      name: "Copy static files to Google Storage Bucket"
      deploy:
        - provider: script
          script: bash ./infrastructure/prod-deploy/deploy-static-files.sh
          skip_cleanup: true
          on:
            branch: master
notifications:
  email: false
  slack:
    rooms: deptfunstuff:abJKvzApk5SKtcEyAgtswXAv
    on_success: change
    on_failure: change
stages:
  - name: test
