os: linux
services:
- docker
language: python
python:
- '3.6'
before_install:
- sudo rm -f /etc/boto.cfg
install:
- sudo docker --version
- sudo docker-compose --version
jobs:
  include:
  - stage: test
    name: Run test suite
    script: "./dev ci test_suite"
  - script: "./dev ci style"
    name: Run style checker
  # - stage: development deployment
  #   script: skip
  #   name: Deploy development website to Google App Engine
  #   deploy:
  #   - provider: script
  #     script: bash ./infrastructure/dev-deploy/deploy-app.sh
  #     on:
  #       branch: develop
  # - script: skip
  #   name: Update development Google Cloud SQL database
  #   deploy:
  #   - provider: script
  #     script: bash ./infrastructure/dev-deploy/update-content.sh
  #     on:
  #       branch: develop
  # - script: skip
  #   name: Copy development static files to Google Storage Bucket
  #   deploy:
  #   - provider: script
  #     script: bash ./infrastructure/dev-deploy/deploy-static-files.sh
  #     on:
  #       branch: develop
  - stage: production deployment
    script: skip
    name: Deploy production website to Google App Engine
    deploy:
    - provider: script
      script: bash ./infrastructure/prod-deploy/deploy-app.sh
      on:
        branch: master
  - script: skip
    name: Update production Google Cloud SQL database
    deploy:
    - provider: script
      script: bash ./infrastructure/prod-deploy/update-content.sh
      on:
        branch: master
  - script: skip
    name: Copy production static files to Google Storage Bucket
    deploy:
    - provider: script
      script: bash ./infrastructure/prod-deploy/deploy-static-files.sh
      on:
        branch: master
notifications:
  email: false
  slack:
    secure: "hDOfTGDLUhz4wkfu01gFEg12EstmSmLNULZMhhZWtEZacbWVFmfqljjLa//Q8NL8SZL9G0aYxgJ/9PeYJBYkwSgGANSK/MOlCf2EvEarhSbQOawYMIX6rlKeBWd43cQZsUojDRuYKgDD8JgtyC4cdOs2vltcY7BjMdugmfeoNIQJ1isksE6zAGFjvfrNPgmBHOngquD2Bd7yzVOst0VWD/Ci1LvJM25s3VXpRzi3AEfWz1ow7ZN2rHN4vFItNf4KQKL0srprYuaswtY6toHhCNQZH56lSN7EWef7nSfG2UJYoxgG6Yvki02itNhWr+XUaPMwKw72tWn6S5rMuJAy8aSveMldFi/2/8lx8Io6fJbDgC/zQH8Ts+/tIVuINxiCJcnAkGKyEiL6+3xKhYYJtxNqTgjMFj/WOAlstTs4dsfiiRsJDo5udpRyQ1LnsaGrzrkq7FlCueBO4/b3BMO5SY58HmbfvGcvim0U36VqKmND1qG97nfRC+cRis7/ZibF5POx4DMW4pnY0HyRet+nMOmuS6mfVYXaol+Cc/V1RJDg7/H8PRcOEAunKIdawX6pRIotR9zGDV+v5/6bRDF8IhzXhd7/G3GFzmUUPP3hVn8m1Ok8/fmGsn1++ILt2/OnCQAXnB+Ss0oHu4n+qqV4j7YEzKYTR2rJ7x46OAXTGrs="
    on_success: change
    on_failure: change
stages:
- name: test
# - name: development deployment
#   if: branch = develop
- name: production deployment
  if: branch = master
