version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    restart: always
    build:
      context: .
      dockerfile: ./infrastructure/postgres/Dockerfile
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    # Set port to non-standard value to not use Travis CI Postgres server.
    command: postgres -p 5434

  django:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    command: /dthm4kaiako/dthm4kaiako/docker-development-entrypoint.sh
    volumes:
      - .:/dthm4kaiako
    environment:
      - PORT=8080
      - USE_DOCKER=yes
      - DATABASE_URL=postgres://postgres@postgres:5434/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - INCLUDE_INCONTEXT_L10N=False
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./infrastructure/nginx/Dockerfile
    volumes:
      - ./dthm4kaiako/:/app/
      - /app/node_modules
    depends_on:
      - django
    ports:
      - "82:80"
