version: '3'
services:
  postgres:
    restart: always
    image: postgres:9.6.8
    # Set port to non-standard value to not use Travis CI Postgres server.
    command: postgres -p 5434

  django:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    command: /cs4teachers/cs4teachers/docker-development-entrypoint.sh
    volumes:
      - .:/cs4teachers
    environment:
      - PORT=8080
      - USE_DOCKER=yes
      - DATABASE_URL=postgres://postgres@postgres:5434/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./infrastructure/nginx/Dockerfile
    volumes:
      - ./cs4teachers/:/app/
      - /app/node_modules
    depends_on:
      - django
    ports:
      - "82:80"
