version: '3'
services:
  cloud_sql_proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    volumes:
      - .:/dthm4kaiako
    command: /cloud_sql_proxy -instances=${GOOGLE_CLOUD_SQL_CONNECTION_NAME}=tcp:0.0.0.0:5432 -credential_file=/dthm4kaiako/${GOOGLE_APPLICATION_CREDENTIALS}

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./dthm4kaiako:/dthm4kaiako/
    environment:
      - USE_DOCKER=yes
      - DJANGO_SETTINGS_MODULE=config.settings.database_proxy
      - GOOGLE_CLOUD_SQL_DATABASE_USERNAME=${GOOGLE_CLOUD_SQL_DATABASE_USERNAME}
      - GOOGLE_CLOUD_SQL_DATABASE_PASSWORD=${GOOGLE_CLOUD_SQL_DATABASE_PASSWORD}
      - GOOGLE_CLOUD_SQL_CONNECTION_NAME=${GOOGLE_CLOUD_SQL_CONNECTION_NAME}
      - GOOGLE_CLOUD_STORAGE_BUCKET_NAME=${GOOGLE_CLOUD_STORAGE_BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - INCLUDE_INCONTEXT_L10N=${INCLUDE_INCONTEXT_L10N}
    depends_on:
      - cloud_sql_proxy

  nginx:
    build:
      context: .
      dockerfile: ./infrastructure/nginx/Dockerfile
    volumes:
      - ./dthm4kaiako/:/app/
      - /app/node_modules
    depends_on:
      - django
