name: Deployment - Dev server

on:
  push:
    # branches:
    #    - develop
  workflow_dispatch:

env:
  DEPLOYMENT: dev
  INCLUDE_INCONTEXT_L10N: false

jobs:
  deploy-app:
    name: Deploy dev website to Google App Engine
    runs-on: ubuntu-20.04
    environment: dev-deployment
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Google Could SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project: dthm4kaiako-dev
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - name: Setup Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Create app.yaml file
      uses: python ./infrastructure/replace_envs.py ./infrastructure/dev-deploy/app.yaml
    # Current doesn't run system 'start' or 'run' commands
    - name: Deploy app
      uses: google-github-actions/deploy-appengine@main
      with:
        deliverables: app.yaml ./infrastructure/dev-deploy/cron.yaml

  # update-database:
  #   name: Update dev Google Cloud SQL database
  #   runs-on: ubuntu-20.04
  #   environment: dev-deployment
  #   - name: Checkout repository
  #     uses: actions/checkout@v2
  #   - name: Update database
  #     run: ./infrastructure/dev-deploy/update-content.sh
  # deploy-static-files:
  #   name: Deploy dev static files to Google Storage Bucket
  #   runs-on: ubuntu-20.04
  #   environment: dev-deployment
  #   - name: Checkout repository
  #     uses: actions/checkout@v2
  #   - name: Deploy static files
  #     run: ./infrastructure/dev-deploy/deploy-static-files.sh
