name: Tests

on: [push, pull_request]

jobs:
  test-suite:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run test suite
      run: ./dev ci test_suite
  style-checker:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run style checker
      run: ./dev ci style
